buildscript {

    repositories {

        google()
        mavenCentral()
        gradlePluginPortal()
    }

    dependencies {

        classpath 'com.android.tools.build:gradle:9.4.0'
        classpath "com.github.plnice:canidropjetifier:0.5"
    }
}

allprojects {

    repositories {

        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven {
            url "https://nexus.web.cern.ch/nexus/content/groups/public/"
        }
        maven {
            url "https://artifactory.appodeal.com/appodeal-public"
        }
    }
}

tasks.register('clean', Delete) {

    delete rootProject.layout.buildDirectory
}

apply plugin: "com.github.plnice.canidropjetifier"
